### ISSUE TITLE
Enforce rate limit constraints and expose them in the settings

### ISSUE THREAD

**Issue by sbellity** [hull-ships/hull-outgoing-webhooks#1]
Users should be able to configure the rate limit contracts of their webhooks endpoint in the connector settings. 

- [ ] Rate limits should be expressed in number of requests per second
- [ ] we could also expose a maximum concurrency for inflight requests

**Comment by michaloo** [comment]
@mathieu sent me the other day this video https://www.youtube.com/watch?v=m64SWl9bfvk&app=desktop

I think we could rely only on the concurrency setting, the transaction rate limit will be then a resulting variable from equation including average response time. So if customer wants to achieve 10 request per second and he knows that the api webhook responds with average of 200 milliseconds he should set concurrency to 2 inflight request.
From our perspective it makes the whole thing much easier we would just need to use [Promise.map](http://bluebirdjs.com/docs/api/promise.map.html) from Bluebird with concurrency setting.
Also we can easily calculate the maximum flow size param after processing first one knowing what is the average response time.
No need for bottleneck/throttle plugin in this case.
